name: proksee
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.7
- fastp
- skesa
- refseq_masher==0.1.2
- quast
- scipy
- spades
- pip
- pip:
  - .
  - numpy==1.19.5
  - scikit-learn==0.24.1
  - joblib==1.0.1
