name: proksee
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.7
- fastp
- skesa
- mash
- quast=5.0.2
- scipy
- spades
- wget
- pip
- pip:
  - .
  - numpy==1.19.5
  - scikit-learn==0.24.1
  - joblib==1.0.1
