name: proksee
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.7
- fastp
- skesa
- refseq_masher
- quast
- scipy
- spades
- pip
- scikit-learn=0.24.1
# - numpy=1.19.5
- joblib=1.0.1
- pip:
  - .
