name: Proksee CMD Linting and Tests for push and PR
on: [push, pull_request]

jobs:
  flake8:
    name: Lint Python scripts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flake8
      run: pip install flake8 flake8-import-order
    - name: Flake8
      run: flake8
